version: "3.8"
services:
  mongodb:
    image: mongo:5.0
    container_name: microservice-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: microservice_db
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  polling-service:
    build: "./polling-service"
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/microservice_db?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
    restart: on-failure
    networks:
      - microservice-network

  user-service:
    build: "./user-service"
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/microservice_db?authSource=admin
      - JWT_SECRET=mysecret
    depends_on:
      mongodb:
        condition: service_healthy
    restart: on-failure
    networks:
      - microservice-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - polling-service
      - user-service
    networks:
      - microservice-network

volumes:
  mongodb_data:
    driver: local

networks:
  microservice-network:
    driver: bridge
