version: "3"
services:
  polling-service:
    build: "./polling-service"
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb+srv://neil:neil260598@collectapp.joovi.mongodb.net/pollingdb?retryWrites=true&w=majority

  user-service:
    build: "./user-service"
    ports:
      - "8001:8000"
    environment:
      - MONGODB_URI=mongodb+srv://neil:neil260598@collectapp.joovi.mongodb.net/pollingdb?retryWrites=true&w=majority
      - JWT_SECRET=miCroSerViCeAppSe!@3423Rvice

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - polling-service
      - user-service
