version: "3"
services:
  polling-service:
    build: "./polling-service"
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=<enter_mongo_uri>

  user-service:
    build: "./user-service"
    ports:
      - "8001:8000"
    environment:
      - MONGODB_URI=<enter_mongo_uri>
      - JWT_SECRET=<enter_jwt_secret>

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - polling-service
      - user-service
