apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
    containers:
      - name: mongodb
        image: mongo:5.0
        ports:
          - containerPort: 27017
            name: mongodb
        envFrom:
          - secretRef: microservice-secrets
        volumeMounts:
          - name: mongodb-persistent-storage
            mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-persistent-storage
      spec:
        accessMode: ["ReadWriteOnce"]
        resource:
          requests:
            storage: 1Gi
