apiVersion: apps/v1
kind: Deployment
metadata:
  name: polling-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polling-service
  template:
    metadata:
      labels:
        app: polling-service
    spec:
      containers:
        - name: polling-service
          image: neilchauhan2/pollapp-polling-service:23
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef: microservice-secrets
          env:
            - name: PORT
              value: "8000"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /api/polling/hello
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/polling/hello
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
