name: Polling Service CI

on:
  push:
    branches: [master]
    paths:
      - "polling-service/**"
      - ".github/workflows/polling-service-ci.yml"
  pull_request:
    branches: [master]
    paths:
      - "polling-service/**"
      - ".github/workflows/polling-service-ci.yml"

jobs:
  test:
    name: Test Polling Service
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./polling-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: ./polling-service/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build-and-push:
    name: Build and Push Docker Image for Polling Service
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./polling-service
          file: ./polling-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pollapp-polling-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/pollapp-polling-service:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout Manifests
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.POLLAPP_PAT }}

      - name: Update K8s manifests with new image tag
        run: |
          IMAGE_TAG=${{ github.run_number }}
          echo "Updating deployment manifest to use image tag: ${IMAGE_TAG}"
          sed -i "s|image: ${{ secrets.DOCKERHUB_USERNAME }}/pollapp-polling-service:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/pollapp-polling-service:${IMAGE_TAG}|g" kubernetes/polling-service-deployment.yaml

      - name: Commit and Push updated manifests
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@github.com'
          git add kubernetes/polling-service-deployment.yaml
          if git diff --staged --quiet; then
            echo "No manifest changes detected."
          else
            echo "Committing and pushing manifest changes..."
            git commit -m "Update polling-service image to build #${{ github.run_number }}"
            git push
          fi
